### ISSUE TITLE
license

### ISSUE THREAD

**Issue by psifertex** [hugsy/binja-retdec#4]
Given the more restrictive retdec API license, it's probably a good idea to include more details about the restrictions in the description so people using the plugin are aware of the additional restrictions. (non-commercial use only, governed by these terms: https://retdec.com/legal-info/)

**Comment by hugsy** [comment]
The RetDec license is one of the reason I was asked to remove the default API key from the previous version. By getting a new API key, you must register and therefore "should" be aware of the restrictions of RetDec license.

But ok, I can drop a note on it.

**Comment by hugsy** [comment]
Done by commit 1254b25
